import React, { createContext, ReactNode, useContext, useEffect, useMemo, useState } from 'react';

export type LanguageCode = 'en' | 'hi' | 'bn' | 'ta' | 'te' | 'mr' | 'gu' | 'kn' | 'ml' | 'or' | 'pa' | 'as' | 'ur';

export const LANGUAGES: Array<{ code: LanguageCode; label: string }> = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'हिन्दी' },
  { code: 'bn', label: 'বাংলা' },
  { code: 'ta', label: 'தமிழ்' },
  { code: 'te', label: 'తెలుగు' },
  { code: 'mr', label: 'मराठी' },
  { code: 'gu', label: 'ગુજરાતી' },
  { code: 'kn', label: 'ಕನ್ನಡ' },
  { code: 'ml', label: 'മലയാളം' },
  { code: 'or', label: 'ଓଡ଼ିଆ' },
  { code: 'pa', label: 'ਪੰਜਾਬੀ' },
  { code: 'as', label: 'অসমীয়া' },
  { code: 'ur', label: 'اردو' },
];

interface LanguageContextType {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const STORAGE_KEY = 'samitibook-language';

const en = {
  'app.name': 'SamitiBook',
  'app.tagline': 'Transparent Festival Management',
  'language.label': 'Language',
  'status.online': 'System Online',
  'nav.main': 'Main Menu',
  'nav.system': 'System',
  'nav.dashboard': 'Dashboard',
  'nav.members': 'Members',
  'nav.orgChart': 'Org Chart',
  'nav.chandaDonations': 'Chanda & Donations',
  'nav.expenses': 'Expenses',
  'nav.inventory': 'Inventory',
  'nav.analytics': 'Analytics',
  'nav.broadcasts': 'Broadcasts',
  'nav.pujaEditions': 'Puja Editions',
  'nav.roleManagement': 'Role Management',
  'nav.settings': 'Settings',
  'auth.adminPortal': 'Admin Portal',
  'auth.adminPortalSubtitle': 'Master access for authorized organizers',
  'auth.memberSync': 'Member Sync',
  'auth.memberSyncSubtitle': 'Access with mobile number and permanent code',
  'auth.emailAddress': 'Email Address',
  'auth.password': 'Password',
  'auth.phoneNumber': 'Phone Number',
  'auth.permanentCode': 'Permanent Login Code',
  'auth.accessDashboard': 'Access Dashboard',
  'auth.memberDashboard': 'Access Member Dashboard',
  'auth.memberHelp': 'Use the permanent code shared by your committee admin. Do not share this code with anyone outside your committee.',
  'auth.memberLogin': 'Member Login',
  'auth.adminLogin': 'Admin Login',
  'auth.adminLoginEmail': 'Admin Login with Email',
  'auth.memberLoginCode': 'Login as Member with Mobile Code',
  'auth.registerCommittee': 'Register Committee',
  'auth.signUpPrompt': 'Need to register a new committee?',
  'auth.signUp': 'Sign Up',
  'common.or': 'or',
  'landing.adminAccess': 'Admin Portal Access',
  'landing.heroCopy': 'A simple, modern operating system for festival committees to manage members, collections, donations, expenses, inventory, and communications with clarity.',
  'landing.liveOverview': 'Live Overview',
  'landing.capabilities': 'Capabilities',
  'landing.builtFor': 'Built for clear committee work.',
  'landing.roleAccess': 'Role-Based Access',
  'landing.roleAccessDesc': 'Give organizers the right permissions without exposing every ledger.',
  'landing.financeRecords': 'Finance Records',
  'landing.financeRecordsDesc': 'Track chanda, donations, expenses, and receipts in one place.',
  'landing.simpleAnalytics': 'Simple Analytics',
  'landing.simpleAnalyticsDesc': 'Understand collection progress, spending, and surplus quickly.',
  'landing.broadcasts': 'Broadcasts',
  'landing.broadcastsDesc': 'Send clear updates to the committee and role groups.',
  'landing.secureAccess': 'Secure Access',
  'landing.secureAccessDesc': 'D1-backed sessions protect committee data.',
  'landing.easyLookup': 'Easy Lookup',
  'landing.easyLookupDesc': 'Use committee IDs to keep demo and real workflows organized.',
  'landing.collections': 'Collections',
  'landing.expenses': 'Expenses',
  'landing.members': 'Members',
  'landing.surplus': 'Surplus',
  'landing.footer': '© 2026 SamitiBook. Transparent Festival Management.',
  'landing.registerDialogTitle': 'Before you register',
  'landing.registerDialogIntro': 'Registration creates a new SamitiBook workspace for one real festival committee. Please read this before creating committee data.',
  'landing.registerCreatesTitle': 'What registration creates',
  'landing.registerCreatesOne': 'A committee workspace with one primary admin account.',
  'landing.registerCreatesTwo': 'A place to manage members, roles, collections, donations, expenses, inventory, broadcasts, and settings.',
  'landing.registerCreatesThree': 'A committee ID that members will use to identify the correct organization.',
  'landing.dosTitle': 'Dos and don’ts',
  'landing.registerDosOne': 'Register only if you are authorized to manage this committee.',
  'landing.registerDosTwo': 'One real committee and location should not be registered more than once.',
  'landing.registerDosThree': 'Use the correct pandal/location details so duplicate committees are not formed.',
  'landing.rolesTitle': 'Roles in simple words',
  'landing.rolesOne': 'Admin controls the committee profile, members, roles, and major settings.',
  'landing.rolesTwo': 'Secretary, cashier, incharges, and volunteers get access based on responsibility.',
  'landing.rolesThree': 'Members can see information and perform actions only if their assigned role allows it.',
  'landing.memberDialogTitle': 'Before member login',
  'landing.memberDialogIntro': 'Member login is for people already added by a committee admin. Your access depends on your assigned role.',
  'landing.memberCanSeeTitle': 'What members can see',
  'landing.memberCanSeeOne': 'Committee details, dashboards, and activity that your role is allowed to view.',
  'landing.memberCanSeeTwo': 'Finance, inventory, cultural, mandap, or broadcast modules only when your role permits it.',
  'landing.memberCanSeeThree': 'Your committee information after logging in with the phone number added by your admin.',
  'landing.memberDosOne': 'Use only your own phone number added by your committee admin.',
  'landing.memberDosTwo': 'Do not share your permanent login code with anyone.',
  'landing.memberDosThree': 'Contact your admin if your phone number is not recognized.',
  'register.title': 'Register Committee',
  'register.subtitle': 'Launch your professional festival operations',
  'register.committeeName': 'Committee Name',
  'register.pujaType': 'Puja Type',
  'register.city': 'City',
  'register.state': 'State',
  'register.pincode': 'Pincode',
  'register.adminPhone': 'Admin Phone',
  'register.pandalLocation': 'Pandal Location',
  'register.pandalHelp': 'Click on the map or search to select your pandal location',
  'register.adminCredentials': 'Admin Credentials',
  'register.adminCredentialsHelp': 'Used for master access and committee oversight.',
  'register.createAccount': 'Create Committee & Account',
  'register.alreadyRegistered': 'Already have a committee?',
  'form.save': 'Save',
  'form.cancel': 'Cancel',
  'form.delete': 'Delete',
  'form.search': 'Search',
  'form.copy': 'Copy',
  'common.loading': 'Loading...',
  'common.approved': 'Approved',
  'common.pending': 'Pending',
  'dashboard.totalDonations': 'Total Donations',
  'dashboard.totalChanda': 'Total Chanda',
  'dashboard.totalExpenses': 'Total Expenses',
  'dashboard.memberCount': 'Member Count',
};

const translations: Record<LanguageCode, Record<string, string>> = {
  en,
  hi: {
    'language.label': 'भाषा',
    'status.online': 'सिस्टम ऑनलाइन',
    'nav.main': 'मुख्य मेनू',
    'nav.system': 'सिस्टम',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.members': 'सदस्य',
    'nav.orgChart': 'संगठन चार्ट',
    'nav.chandaDonations': 'चंदा और दान',
    'nav.expenses': 'खर्च',
    'nav.inventory': 'इन्वेंटरी',
    'nav.analytics': 'विश्लेषण',
    'nav.broadcasts': 'घोषणाएँ',
    'nav.pujaEditions': 'पूजा संस्करण',
    'nav.roleManagement': 'भूमिका प्रबंधन',
    'nav.settings': 'सेटिंग्स',
    'auth.adminPortal': 'एडमिन पोर्टल',
    'auth.adminPortalSubtitle': 'अधिकृत आयोजकों के लिए मुख्य प्रवेश',
    'auth.memberSync': 'सदस्य लॉगिन',
    'auth.memberSyncSubtitle': 'मोबाइल नंबर और स्थायी कोड से प्रवेश',
    'auth.emailAddress': 'ईमेल पता',
    'auth.password': 'पासवर्ड',
    'auth.phoneNumber': 'फोन नंबर',
    'auth.permanentCode': 'स्थायी लॉगिन कोड',
    'auth.accessDashboard': 'डैशबोर्ड खोलें',
    'auth.memberDashboard': 'सदस्य डैशबोर्ड खोलें',
    'auth.memberHelp': 'समिति एडमिन द्वारा दिया गया स्थायी कोड उपयोग करें। यह कोड समिति के बाहर किसी से साझा न करें।',
    'auth.memberLogin': 'सदस्य लॉगिन',
    'auth.adminLogin': 'एडमिन लॉगिन',
    'auth.adminLoginEmail': 'ईमेल से एडमिन लॉगिन',
    'auth.memberLoginCode': 'मोबाइल कोड से सदस्य लॉगिन',
    'auth.registerCommittee': 'समिति पंजीकरण',
    'auth.signUpPrompt': 'नई समिति पंजीकृत करनी है?',
    'auth.signUp': 'साइन अप',
    'common.or': 'या',
    'landing.adminAccess': 'एडमिन पोर्टल प्रवेश',
    'landing.heroCopy': 'समितियों के लिए सदस्य, चंदा, दान, खर्च, इन्वेंटरी और संचार को साफ तरीके से संभालने वाला सरल आधुनिक सिस्टम।',
    'landing.liveOverview': 'लाइव सारांश',
    'landing.capabilities': 'क्षमताएँ',
    'landing.builtFor': 'स्पष्ट समिति कार्य के लिए बनाया गया।',
    'register.title': 'समिति पंजीकरण',
    'register.subtitle': 'अपने त्योहार संचालन को पेशेवर रूप दें',
    'register.committeeName': 'समिति का नाम',
    'register.pujaType': 'पूजा प्रकार',
    'register.city': 'शहर',
    'register.state': 'राज्य',
    'register.pincode': 'पिनकोड',
    'register.adminPhone': 'एडमिन फोन',
    'register.pandalLocation': 'पंडाल स्थान',
    'register.pandalHelp': 'पंडाल स्थान चुनने के लिए मानचित्र पर क्लिक करें या खोजें',
    'register.adminCredentials': 'एडमिन क्रेडेंशियल',
    'register.adminCredentialsHelp': 'मुख्य प्रवेश और समिति निगरानी के लिए उपयोग होगा।',
    'register.createAccount': 'समिति और खाता बनाएँ',
    'register.alreadyRegistered': 'पहले से समिति है?',
    'form.save': 'सेव करें',
    'form.cancel': 'रद्द करें',
    'form.delete': 'हटाएँ',
    'form.search': 'खोजें',
    'form.copy': 'कॉपी करें',
    'common.loading': 'लोड हो रहा है...',
    'common.approved': 'स्वीकृत',
    'common.pending': 'लंबित',
    'dashboard.totalDonations': 'कुल दान',
    'dashboard.totalChanda': 'कुल चंदा',
    'dashboard.totalExpenses': 'कुल खर्च',
    'dashboard.memberCount': 'सदस्य संख्या',
  },
  bn: {
    'language.label': 'ভাষা',
    'app.tagline': 'স্বচ্ছ উৎসব ব্যবস্থাপনা',
    'landing.adminAccess': 'এডমিন পোর্টাল প্রবেশ',
    'landing.heroCopy': 'উৎসব কমিটির জন্য সহজ, আধুনিক অপারেটিং সিস্টেম যেখানে সদস্য, সংগ্রহ, দান, খরচ, ইনভেন্টরি এবং যোগাযোগ পরিষ্কারভাবে পরিচালনা করা যায়।',
    'landing.liveOverview': 'সরাসরি সারাংশ',
    'landing.capabilities': 'সুবিধাসমূহ',
    'landing.builtFor': 'পরিষ্কার কমিটি কাজের জন্য তৈরি।',
    'landing.roleAccess': 'ভূমিকা-ভিত্তিক প্রবেশ',
    'landing.roleAccessDesc': 'প্রতিটি খাতা সবার সামনে না খুলে সংগঠকদের সঠিক অনুমতি দিন।',
    'landing.financeRecords': 'আর্থিক রেকর্ড',
    'landing.financeRecordsDesc': 'চাঁদা, দান, খরচ এবং রসিদ এক জায়গায় রাখুন।',
    'landing.simpleAnalytics': 'সহজ বিশ্লেষণ',
    'landing.simpleAnalyticsDesc': 'সংগ্রহ, খরচ এবং উদ্বৃত্ত দ্রুত বুঝুন।',
    'landing.broadcasts': 'বার্তা',
    'landing.broadcastsDesc': 'কমিটি এবং ভূমিকা-ভিত্তিক দলকে পরিষ্কার আপডেট পাঠান।',
    'landing.secureAccess': 'নিরাপদ প্রবেশ',
    'landing.secureAccessDesc': 'D1-ভিত্তিক সেশন কমিটির তথ্য সুরক্ষিত রাখে।',
    'landing.easyLookup': 'সহজ খোঁজ',
    'landing.easyLookupDesc': 'ডেমো এবং বাস্তব কাজ আলাদা রাখতে কমিটি আইডি ব্যবহার করুন।',
    'landing.collections': 'সংগ্রহ',
    'landing.expenses': 'খরচ',
    'landing.members': 'সদস্য',
    'landing.surplus': 'উদ্বৃত্ত',
    'nav.dashboard': 'ড্যাশবোর্ড',
    'nav.members': 'সদস্য',
    'nav.chandaDonations': 'চাঁদা ও দান',
    'nav.expenses': 'খরচ',
    'nav.inventory': 'ইনভেন্টরি',
    'nav.analytics': 'বিশ্লেষণ',
    'nav.broadcasts': 'বার্তা',
    'nav.settings': 'সেটিংস',
    'auth.adminPortal': 'অ্যাডমিন পোর্টাল',
    'auth.emailAddress': 'ইমেল ঠিকানা',
    'auth.password': 'পাসওয়ার্ড',
    'auth.memberLogin': 'সদস্য লগইন',
    'auth.registerCommittee': 'কমিটি নিবন্ধন',
  },
  ta: {
    'language.label': 'மொழி',
    'nav.dashboard': 'டாஷ்போர்டு',
    'nav.members': 'உறுப்பினர்கள்',
    'nav.chandaDonations': 'சந்தா மற்றும் நன்கொடை',
    'nav.expenses': 'செலவுகள்',
    'nav.inventory': 'சரக்கு',
    'nav.analytics': 'பகுப்பாய்வு',
    'nav.broadcasts': 'அறிவிப்புகள்',
    'nav.settings': 'அமைப்புகள்',
    'auth.adminPortal': 'நிர்வாக போர்டல்',
    'auth.emailAddress': 'மின்னஞ்சல் முகவரி',
    'auth.password': 'கடவுச்சொல்',
    'auth.memberLogin': 'உறுப்பினர் உள்நுழைவு',
    'auth.registerCommittee': 'குழு பதிவு',
  },
  te: {
    'language.label': 'భాష',
    'nav.dashboard': 'డ్యాష్‌బోర్డ్',
    'nav.members': 'సభ్యులు',
    'nav.chandaDonations': 'చందా మరియు విరాళాలు',
    'nav.expenses': 'ఖర్చులు',
    'nav.inventory': 'ఇన్వెంటరీ',
    'nav.analytics': 'విశ్లేషణ',
    'nav.broadcasts': 'ప్రకటనలు',
    'nav.settings': 'సెట్టింగులు',
    'auth.adminPortal': 'అడ్మిన్ పోర్టల్',
    'auth.emailAddress': 'ఇమెయిల్ చిరునామా',
    'auth.password': 'పాస్‌వర్డ్',
    'auth.memberLogin': 'సభ్యుల లాగిన్',
    'auth.registerCommittee': 'సమితి నమోదు',
  },
  mr: {
    'language.label': 'भाषा',
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.members': 'सदस्य',
    'nav.chandaDonations': 'चंदा आणि देणगी',
    'nav.expenses': 'खर्च',
    'nav.inventory': 'इन्व्हेंटरी',
    'nav.analytics': 'विश्लेषण',
    'nav.broadcasts': 'घोषणा',
    'nav.settings': 'सेटिंग्ज',
    'auth.adminPortal': 'अॅडमिन पोर्टल',
    'auth.emailAddress': 'ईमेल पत्ता',
    'auth.password': 'पासवर्ड',
    'auth.memberLogin': 'सदस्य लॉगिन',
    'auth.registerCommittee': 'समिती नोंदणी',
  },
  gu: {
    'language.label': 'ભાષા',
    'nav.dashboard': 'ડેશબોર્ડ',
    'nav.members': 'સભ્યો',
    'nav.chandaDonations': 'ચંદા અને દાન',
    'nav.expenses': 'ખર્ચ',
    'nav.inventory': 'ઇન્વેન્ટરી',
    'nav.analytics': 'વિશ્લેષણ',
    'nav.broadcasts': 'જાહેરાતો',
    'nav.settings': 'સેટિંગ્સ',
    'auth.adminPortal': 'એડમિન પોર્ટલ',
    'auth.emailAddress': 'ઈમેલ સરનામું',
    'auth.password': 'પાસવર્ડ',
    'auth.memberLogin': 'સભ્ય લોગિન',
    'auth.registerCommittee': 'સમિતિ નોંધણી',
  },
  kn: {
    'language.label': 'ಭಾಷೆ',
    'nav.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'nav.members': 'ಸದಸ್ಯರು',
    'nav.chandaDonations': 'ಚಂದಾ ಮತ್ತು ದೇಣಿಗೆ',
    'nav.expenses': 'ಖರ್ಚುಗಳು',
    'nav.inventory': 'ಇನ್ವೆಂಟರಿ',
    'nav.analytics': 'ವಿಶ್ಲೇಷಣೆ',
    'nav.broadcasts': 'ಪ್ರಕಟನೆಗಳು',
    'nav.settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'auth.adminPortal': 'ನಿರ್ವಾಹಕ ಪೋರ್ಟಲ್',
    'auth.emailAddress': 'ಇಮೇಲ್ ವಿಳಾಸ',
    'auth.password': 'ಪಾಸ್‌ವರ್ಡ್',
    'auth.memberLogin': 'ಸದಸ್ಯ ಲಾಗಿನ್',
    'auth.registerCommittee': 'ಸಮಿತಿ ನೋಂದಣಿ',
  },
  ml: {
    'language.label': 'ഭാഷ',
    'nav.dashboard': 'ഡാഷ്ബോർഡ്',
    'nav.members': 'അംഗങ്ങൾ',
    'nav.chandaDonations': 'ചന്ദയും സംഭാവനയും',
    'nav.expenses': 'ചെലവുകൾ',
    'nav.inventory': 'ഇൻവെന്ററി',
    'nav.analytics': 'വിശകലനം',
    'nav.broadcasts': 'അറിയിപ്പുകൾ',
    'nav.settings': 'ക്രമീകരണങ്ങൾ',
    'auth.adminPortal': 'അഡ്മിൻ പോർട്ടൽ',
    'auth.emailAddress': 'ഇമെയിൽ വിലാസം',
    'auth.password': 'പാസ്‌വേഡ്',
    'auth.memberLogin': 'അംഗ ലോഗിൻ',
    'auth.registerCommittee': 'സമിതി രജിസ്ട്രേഷൻ',
  },
  or: {
    'language.label': 'ଭାଷା',
    'nav.dashboard': 'ଡ୍ୟାଶବୋର୍ଡ',
    'nav.members': 'ସଦସ୍ୟ',
    'nav.chandaDonations': 'ଚାନ୍ଦା ଓ ଦାନ',
    'nav.expenses': 'ଖର୍ଚ୍ଚ',
    'nav.inventory': 'ଇନଭେଣ୍ଟରୀ',
    'nav.analytics': 'ବିଶ୍ଳେଷଣ',
    'nav.broadcasts': 'ଘୋଷଣା',
    'nav.settings': 'ସେଟିଂସ୍',
    'auth.adminPortal': 'ଆଡମିନ ପୋର୍ଟାଲ',
    'auth.emailAddress': 'ଇମେଲ ଠିକଣା',
    'auth.password': 'ପାସୱାର୍ଡ',
    'auth.memberLogin': 'ସଦସ୍ୟ ଲଗଇନ',
    'auth.registerCommittee': 'ସମିତି ପଞ୍ଜିକରଣ',
  },
  pa: {
    'language.label': 'ਭਾਸ਼ਾ',
    'nav.dashboard': 'ਡੈਸ਼ਬੋਰਡ',
    'nav.members': 'ਮੈਂਬਰ',
    'nav.chandaDonations': 'ਚੰਦਾ ਅਤੇ ਦਾਨ',
    'nav.expenses': 'ਖਰਚੇ',
    'nav.inventory': 'ਇਨਵੈਂਟਰੀ',
    'nav.analytics': 'ਵਿਸ਼ਲੇਸ਼ਣ',
    'nav.broadcasts': 'ਐਲਾਨ',
    'nav.settings': 'ਸੈਟਿੰਗਾਂ',
    'auth.adminPortal': 'ਐਡਮਿਨ ਪੋਰਟਲ',
    'auth.emailAddress': 'ਈਮੇਲ ਪਤਾ',
    'auth.password': 'ਪਾਸਵਰਡ',
    'auth.memberLogin': 'ਮੈਂਬਰ ਲਾਗਇਨ',
    'auth.registerCommittee': 'ਸਮਿਤੀ ਰਜਿਸਟ੍ਰੇਸ਼ਨ',
  },
  as: {
    'language.label': 'ভাষা',
    'nav.dashboard': 'ডেশ্ববৰ্ড',
    'nav.members': 'সদস্য',
    'nav.chandaDonations': 'চাঁদা আৰু দান',
    'nav.expenses': 'খৰচ',
    'nav.inventory': 'ইনভেণ্টৰি',
    'nav.analytics': 'বিশ্লেষণ',
    'nav.broadcasts': 'ঘোষণা',
    'nav.settings': 'ছেটিংছ',
    'auth.adminPortal': 'এডমিন পৰ্টেল',
    'auth.emailAddress': 'ইমেইল ঠিকনা',
    'auth.password': 'পাছৱৰ্ড',
    'auth.memberLogin': 'সদস্য লগইন',
    'auth.registerCommittee': 'সমিতি পঞ্জীয়ন',
  },
  ur: {
    'language.label': 'زبان',
    'nav.dashboard': 'ڈیش بورڈ',
    'nav.members': 'اراکین',
    'nav.orgChart': 'تنظیمی چارٹ',
    'nav.chandaDonations': 'چندہ اور عطیات',
    'nav.expenses': 'اخراجات',
    'nav.inventory': 'انوینٹری',
    'nav.analytics': 'تجزیات',
    'nav.broadcasts': 'اعلانات',
    'nav.settings': 'ترتیبات',
    'auth.adminPortal': 'ایڈمن پورٹل',
    'auth.adminPortalSubtitle': 'مجاز منتظمین کے لیے مرکزی رسائی',
    'auth.emailAddress': 'ای میل پتہ',
    'auth.password': 'پاس ورڈ',
    'auth.accessDashboard': 'ڈیش بورڈ کھولیں',
    'auth.memberLogin': 'رکن لاگ ان',
    'auth.registerCommittee': 'سمیتی رجسٹریشن',
  },
};

const landingText: Partial<Record<LanguageCode, Record<string, string>>> = {
  hi: {
    'app.tagline': 'पारदर्शी उत्सव प्रबंधन',
    'landing.footer': '© 2026 SamitiBook. पारदर्शी उत्सव प्रबंधन।',
    'landing.collections': 'संग्रह',
    'landing.expenses': 'खर्च',
    'landing.members': 'सदस्य',
    'landing.surplus': 'अधिशेष',
    'landing.roleAccess': 'भूमिका-आधारित प्रवेश',
    'landing.roleAccessDesc': 'हर खाता खोले बिना आयोजकों को सही अनुमति दें।',
    'landing.financeRecords': 'वित्त रिकॉर्ड',
    'landing.financeRecordsDesc': 'चंदा, दान, खर्च और रसीदें एक जगह रखें।',
    'landing.simpleAnalytics': 'सरल विश्लेषण',
    'landing.simpleAnalyticsDesc': 'संग्रह, खर्च और अधिशेष जल्दी समझें।',
    'landing.broadcasts': 'घोषणाएँ',
    'landing.broadcastsDesc': 'समिति और भूमिका समूहों को साफ अपडेट भेजें।',
    'landing.secureAccess': 'सुरक्षित प्रवेश',
    'landing.secureAccessDesc': 'D1-आधारित सत्र समिति डेटा सुरक्षित रखते हैं।',
    'landing.easyLookup': 'आसान खोज',
    'landing.easyLookupDesc': 'डेमो और वास्तविक काम अलग रखने के लिए समिति आईडी उपयोग करें।',
    'landing.registerDialogTitle': 'पंजीकरण से पहले',
    'landing.registerDialogIntro': 'पंजीकरण एक वास्तविक उत्सव समिति के लिए नया SamitiBook कार्यक्षेत्र बनाता है। डेटा बनाने से पहले इसे पढ़ें।',
    'landing.registerCreatesTitle': 'पंजीकरण क्या बनाता है',
    'landing.registerCreatesOne': 'एक प्राथमिक एडमिन खाते वाला समिति कार्यक्षेत्र।',
    'landing.registerCreatesTwo': 'सदस्य, भूमिका, संग्रह, दान, खर्च, इन्वेंटरी, घोषणाएँ और सेटिंग्स संभालने की जगह।',
    'landing.registerCreatesThree': 'एक समिति आईडी जिससे सदस्य सही संस्था पहचानेंगे।',
    'landing.dosTitle': 'क्या करें और क्या न करें',
    'landing.registerDosOne': 'केवल तभी पंजीकरण करें जब आप इस समिति को संभालने के लिए अधिकृत हों।',
    'landing.registerDosTwo': 'एक वास्तविक समिति और स्थान को दो बार पंजीकृत न करें।',
    'landing.registerDosThree': 'सही पंडाल/स्थान विवरण दें ताकि डुप्लिकेट समिति न बने।',
    'landing.rolesTitle': 'भूमिकाएँ आसान शब्दों में',
    'landing.rolesOne': 'एडमिन समिति प्रोफाइल, सदस्य, भूमिकाएँ और मुख्य सेटिंग्स संभालता है।',
    'landing.rolesTwo': 'सेक्रेटरी, कैशियर, इंचार्ज और स्वयंसेवक जिम्मेदारी के अनुसार प्रवेश पाते हैं।',
    'landing.rolesThree': 'सदस्य केवल अपनी भूमिका के अनुसार जानकारी और कार्रवाई देख सकते हैं।',
    'landing.memberDialogTitle': 'सदस्य लॉगिन से पहले',
    'landing.memberDialogIntro': 'सदस्य लॉगिन उन लोगों के लिए है जिन्हें समिति एडमिन ने जोड़ा है। आपका प्रवेश आपकी भूमिका पर निर्भर है।',
    'landing.memberCanSeeTitle': 'सदस्य क्या देख सकते हैं',
    'landing.memberCanSeeOne': 'समिति विवरण, डैशबोर्ड और आपकी भूमिका से अनुमत गतिविधि।',
    'landing.memberCanSeeTwo': 'वित्त, इन्वेंटरी, सांस्कृतिक, मंडप या प्रसारण मॉड्यूल तभी जब भूमिका अनुमति दे।',
    'landing.memberCanSeeThree': 'एडमिन द्वारा जोड़े गए फोन नंबर से लॉगिन करने पर समिति जानकारी।',
    'landing.memberDosOne': 'केवल एडमिन द्वारा जोड़ा गया अपना फोन नंबर उपयोग करें।',
    'landing.memberDosTwo': 'अपना स्थायी लॉगिन कोड किसी से साझा न करें।',
    'landing.memberDosThree': 'फोन नंबर पहचान में न आए तो एडमिन से संपर्क करें।',
  },
  bn: {
    'app.tagline': 'স্বচ্ছ উৎসব ব্যবস্থাপনা',
    'landing.footer': '© 2026 SamitiBook. স্বচ্ছ উৎসব ব্যবস্থাপনা।',
    'landing.adminAccess': 'এডমিন পোর্টাল প্রবেশ',
    'landing.heroCopy': 'উৎসব কমিটির জন্য সহজ, আধুনিক অপারেটিং সিস্টেম যেখানে সদস্য, সংগ্রহ, দান, খরচ, ইনভেন্টরি এবং যোগাযোগ পরিষ্কারভাবে পরিচালনা করা যায়।',
    'landing.liveOverview': 'সরাসরি সারাংশ',
    'landing.capabilities': 'সুবিধাসমূহ',
    'landing.builtFor': 'পরিষ্কার কমিটি কাজের জন্য তৈরি।',
    'landing.roleAccess': 'ভূমিকা-ভিত্তিক প্রবেশ',
    'landing.roleAccessDesc': 'প্রতিটি খাতা সবার সামনে না খুলে সংগঠকদের সঠিক অনুমতি দিন।',
    'landing.financeRecords': 'আর্থিক রেকর্ড',
    'landing.financeRecordsDesc': 'চাঁদা, দান, খরচ এবং রসিদ এক জায়গায় রাখুন।',
    'landing.simpleAnalytics': 'সহজ বিশ্লেষণ',
    'landing.simpleAnalyticsDesc': 'সংগ্রহ, খরচ এবং উদ্বৃত্ত দ্রুত বুঝুন।',
    'landing.broadcasts': 'বার্তা',
    'landing.broadcastsDesc': 'কমিটি এবং ভূমিকা-ভিত্তিক দলকে পরিষ্কার আপডেট পাঠান।',
    'landing.secureAccess': 'নিরাপদ প্রবেশ',
    'landing.secureAccessDesc': 'D1-ভিত্তিক সেশন কমিটির তথ্য সুরক্ষিত রাখে।',
    'landing.easyLookup': 'সহজ খোঁজ',
    'landing.easyLookupDesc': 'ডেমো এবং বাস্তব কাজ আলাদা রাখতে কমিটি আইডি ব্যবহার করুন।',
    'landing.collections': 'সংগ্রহ',
    'landing.expenses': 'খরচ',
    'landing.members': 'সদস্য',
    'landing.surplus': 'উদ্বৃত্ত',
    'landing.registerDialogTitle': 'নিবন্ধনের আগে',
    'landing.registerDialogIntro': 'নিবন্ধন একটি বাস্তব উৎসব কমিটির জন্য নতুন SamitiBook কর্মক্ষেত্র তৈরি করে। তথ্য তৈরির আগে এটি পড়ুন।',
    'landing.registerCreatesTitle': 'নিবন্ধনে যা তৈরি হয়',
    'landing.registerCreatesOne': 'একটি প্রাথমিক এডমিন অ্যাকাউন্টসহ কমিটির কর্মক্ষেত্র।',
    'landing.registerCreatesTwo': 'সদস্য, ভূমিকা, সংগ্রহ, দান, খরচ, ইনভেন্টরি, বার্তা এবং সেটিংস পরিচালনার জায়গা।',
    'landing.registerCreatesThree': 'একটি কমিটি আইডি যা সদস্যরা সঠিক প্রতিষ্ঠান চিনতে ব্যবহার করবে।',
    'landing.dosTitle': 'করণীয় ও বর্জনীয়',
    'landing.registerDosOne': 'আপনি অনুমোদিত হলে তবেই এই কমিটি নিবন্ধন করুন।',
    'landing.registerDosTwo': 'একই বাস্তব কমিটি ও স্থান একাধিকবার নিবন্ধন করবেন না।',
    'landing.registerDosThree': 'সঠিক প্যান্ডেল/স্থান তথ্য দিন যাতে ডুপ্লিকেট কমিটি না তৈরি হয়।',
    'landing.rolesTitle': 'সহজ কথায় ভূমিকা',
    'landing.rolesOne': 'এডমিন কমিটি প্রোফাইল, সদস্য, ভূমিকা এবং প্রধান সেটিংস নিয়ন্ত্রণ করে।',
    'landing.rolesTwo': 'সেক্রেটারি, ক্যাশিয়ার, ইনচার্জ এবং স্বেচ্ছাসেবক দায়িত্ব অনুযায়ী প্রবেশ পায়।',
    'landing.rolesThree': 'সদস্যরা নিজের ভূমিকা অনুযায়ী তথ্য দেখতে এবং কাজ করতে পারে।',
    'landing.memberDialogTitle': 'সদস্য লগইনের আগে',
    'landing.memberDialogIntro': 'সদস্য লগইন তাদের জন্য যাদের কমিটি এডমিন আগে যোগ করেছেন। আপনার প্রবেশ আপনার ভূমিকার উপর নির্ভর করে।',
    'landing.memberCanSeeTitle': 'সদস্যরা যা দেখতে পারে',
    'landing.memberCanSeeOne': 'কমিটির তথ্য, ড্যাশবোর্ড এবং আপনার ভূমিকার অনুমোদিত কার্যকলাপ।',
    'landing.memberCanSeeTwo': 'ভূমিকা অনুমতি দিলে অর্থ, ইনভেন্টরি, সাংস্কৃতিক, মণ্ডপ বা বার্তা মডিউল।',
    'landing.memberCanSeeThree': 'এডমিন যোগ করা ফোন নম্বর দিয়ে লগইন করার পর কমিটির তথ্য।',
    'landing.memberDosOne': 'শুধু আপনার এডমিন যোগ করা নিজের ফোন নম্বর ব্যবহার করুন।',
    'landing.memberDosTwo': 'আপনার স্থায়ী লগইন কোড কারও সঙ্গে শেয়ার করবেন না।',
    'landing.memberDosThree': 'ফোন নম্বর চেনা না গেলে এডমিনের সঙ্গে যোগাযোগ করুন।',
  },
  ta: {
    'app.tagline': 'வெளிப்படையான விழா மேலாண்மை',
    'landing.adminAccess': 'நிர்வாக போர்டல் அணுகல்',
    'landing.heroCopy': 'விழா குழுக்கள் உறுப்பினர்கள், வசூல், நன்கொடை, செலவு, சரக்கு மற்றும் தொடர்புகளை தெளிவாக நிர்வகிக்க உதவும் எளிய நவீன அமைப்பு.',
    'landing.liveOverview': 'நேரடி கண்ணோட்டம்',
    'landing.capabilities': 'திறன்கள்',
    'landing.builtFor': 'தெளிவான குழு பணிக்காக உருவாக்கப்பட்டது.',
    'landing.collections': 'வசூல்',
    'landing.expenses': 'செலவுகள்',
    'landing.members': 'உறுப்பினர்கள்',
    'landing.surplus': 'மீதம்',
    'landing.footer': '© 2026 SamitiBook. வெளிப்படையான விழா மேலாண்மை.',
  },
  te: {
    'app.tagline': 'పారదర్శక ఉత్సవ నిర్వహణ',
    'landing.adminAccess': 'అడ్మిన్ పోర్టల్ యాక్సెస్',
    'landing.heroCopy': 'ఉత్సవ కమిటీలు సభ్యులు, వసూళ్లు, విరాళాలు, ఖర్చులు, ఇన్వెంటరీ మరియు సమాచారాన్ని స్పష్టంగా నిర్వహించేందుకు సరళమైన ఆధునిక వ్యవస్థ.',
    'landing.liveOverview': 'ప్రత్యక్ష సారాంశం',
    'landing.capabilities': 'సామర్థ్యాలు',
    'landing.builtFor': 'స్పష్టమైన కమిటీ పనికి రూపొందించబడింది.',
    'landing.collections': 'వసూళ్లు',
    'landing.expenses': 'ఖర్చులు',
    'landing.members': 'సభ్యులు',
    'landing.surplus': 'మిగులు',
    'landing.footer': '© 2026 SamitiBook. పారదర్శక ఉత్సవ నిర్వహణ.',
  },
  mr: {
    'app.tagline': 'पारदर्शक उत्सव व्यवस्थापन',
    'landing.adminAccess': 'अॅडमिन पोर्टल प्रवेश',
    'landing.heroCopy': 'उत्सव समित्यांसाठी सदस्य, संकलन, देणगी, खर्च, इन्व्हेंटरी आणि संवाद स्पष्टपणे व्यवस्थापित करणारी सोपी आधुनिक प्रणाली.',
    'landing.liveOverview': 'थेट आढावा',
    'landing.capabilities': 'क्षमता',
    'landing.builtFor': 'स्पष्ट समिती कामासाठी तयार.',
    'landing.collections': 'संकलन',
    'landing.expenses': 'खर्च',
    'landing.members': 'सदस्य',
    'landing.surplus': 'अधिशेष',
    'landing.footer': '© 2026 SamitiBook. पारदर्शक उत्सव व्यवस्थापन.',
  },
  gu: {
    'app.tagline': 'પારદર્શક ઉત્સવ વ્યવસ્થાપન',
    'landing.adminAccess': 'એડમિન પોર્ટલ પ્રવેશ',
    'landing.heroCopy': 'ઉત્સવ સમિતિઓ માટે સભ્યો, વસુલાત, દાન, ખર્ચ, ઇન્વેન્ટરી અને સંચારને સ્પષ્ટ રીતે સંચાલિત કરતું સરળ આધુનિક સિસ્ટમ.',
    'landing.liveOverview': 'લાઇવ સારાંશ',
    'landing.capabilities': 'ક્ષમતાઓ',
    'landing.builtFor': 'સ્પષ્ટ સમિતિ કાર્ય માટે બનાવ્યું.',
    'landing.collections': 'વસુલાત',
    'landing.expenses': 'ખર્ચ',
    'landing.members': 'સભ્યો',
    'landing.surplus': 'વધારું',
    'landing.footer': '© 2026 SamitiBook. પારદર્શક ઉત્સવ વ્યવસ્થાપન.',
  },
  kn: {
    'app.tagline': 'ಪಾರದರ್ಶಕ ಹಬ್ಬ ನಿರ್ವಹಣೆ',
    'landing.adminAccess': 'ನಿರ್ವಾಹಕ ಪೋರ್ಟಲ್ ಪ್ರವೇಶ',
    'landing.heroCopy': 'ಹಬ್ಬ ಸಮಿತಿಗಳಿಗೆ ಸದಸ್ಯರು, ಸಂಗ್ರಹ, ದೇಣಿಗೆ, ಖರ್ಚು, ಇನ್ವೆಂಟರಿ ಮತ್ತು ಸಂವಹನವನ್ನು ಸ್ಪಷ್ಟವಾಗಿ ನಿರ್ವಹಿಸುವ ಸರಳ ಆಧುನಿಕ ವ್ಯವಸ್ಥೆ.',
    'landing.liveOverview': 'ನೇರ ಸಾರಾಂಶ',
    'landing.capabilities': 'ಸಾಮರ್ಥ್ಯಗಳು',
    'landing.builtFor': 'ಸ್ಪಷ್ಟ ಸಮಿತಿ ಕೆಲಸಕ್ಕಾಗಿ ನಿರ್ಮಿಸಲಾಗಿದೆ.',
    'landing.collections': 'ಸಂಗ್ರಹ',
    'landing.expenses': 'ಖರ್ಚುಗಳು',
    'landing.members': 'ಸದಸ್ಯರು',
    'landing.surplus': 'ಮಿಗುಲು',
    'landing.footer': '© 2026 SamitiBook. ಪಾರದರ್ಶಕ ಹಬ್ಬ ನಿರ್ವಹಣೆ.',
  },
  ml: {
    'app.tagline': 'സുതാര്യ ഉത്സവ മാനേജ്മെന്റ്',
    'landing.adminAccess': 'അഡ്മിൻ പോർട്ടൽ പ്രവേശനം',
    'landing.heroCopy': 'ഉത്സവ കമ്മിറ്റികൾക്ക് അംഗങ്ങൾ, പിരിവ്, സംഭാവന, ചെലവ്, ഇൻവെന്ററി, ആശയവിനിമയം എന്നിവ വ്യക്തമായി നിയന്ത്രിക്കാൻ സഹായിക്കുന്ന ലളിതമായ ആധുനിക സംവിധാനം.',
    'landing.liveOverview': 'ലൈവ് അവലോകനം',
    'landing.capabilities': 'സൗകര്യങ്ങൾ',
    'landing.builtFor': 'വ്യക്തമായ കമ്മിറ്റി പ്രവർത്തനത്തിനായി നിർമ്മിച്ചത്.',
    'landing.collections': 'പിരിവ്',
    'landing.expenses': 'ചെലവുകൾ',
    'landing.members': 'അംഗങ്ങൾ',
    'landing.surplus': 'മിച്ചം',
    'landing.footer': '© 2026 SamitiBook. സുതാര്യ ഉത്സവ മാനേജ്മെന്റ്.',
  },
  or: {
    'app.tagline': 'ସ୍ୱଚ୍ଛ ଉତ୍ସବ ପରିଚାଳନା',
    'landing.adminAccess': 'ଆଡମିନ ପୋର୍ଟାଲ ପ୍ରବେଶ',
    'landing.heroCopy': 'ଉତ୍ସବ ସମିତି ପାଇଁ ସଦସ୍ୟ, ସଂଗ୍ରହ, ଦାନ, ଖର୍ଚ୍ଚ, ଇନଭେଣ୍ଟରୀ ଏବଂ ଯୋଗାଯୋଗକୁ ସ୍ପଷ୍ଟ ଭାବରେ ପରିଚାଳନା କରୁଥିବା ସହଜ ଆଧୁନିକ ପ୍ରଣାଳୀ।',
    'landing.liveOverview': 'ସଜୀବ ସାରାଂଶ',
    'landing.capabilities': 'କ୍ଷମତା',
    'landing.builtFor': 'ସ୍ପଷ୍ଟ ସମିତି କାମ ପାଇଁ ତିଆରି।',
    'landing.collections': 'ସଂଗ୍ରହ',
    'landing.expenses': 'ଖର୍ଚ୍ଚ',
    'landing.members': 'ସଦସ୍ୟ',
    'landing.surplus': 'ଅତିରିକ୍ତ',
    'landing.footer': '© 2026 SamitiBook. ସ୍ୱଚ୍ଛ ଉତ୍ସବ ପରିଚାଳନା.',
  },
  pa: {
    'app.tagline': 'ਪਾਰਦਰਸ਼ੀ ਤਿਉਹਾਰ ਪ੍ਰਬੰਧਨ',
    'landing.adminAccess': 'ਐਡਮਿਨ ਪੋਰਟਲ ਪਹੁੰਚ',
    'landing.heroCopy': 'ਤਿਉਹਾਰ ਕਮੇਟੀਆਂ ਲਈ ਮੈਂਬਰਾਂ, ਇਕੱਠ, ਦਾਨ, ਖਰਚੇ, ਇਨਵੈਂਟਰੀ ਅਤੇ ਸੰਚਾਰ ਨੂੰ ਸਾਫ਼ ਤਰੀਕੇ ਨਾਲ ਸੰਭਾਲਣ ਵਾਲਾ ਸਧਾਰਣ ਆਧੁਨਿਕ ਸਿਸਟਮ।',
    'landing.liveOverview': 'ਲਾਈਵ ਸੰਖੇਪ',
    'landing.capabilities': 'ਸਮਰੱਥਾਵਾਂ',
    'landing.builtFor': 'ਸਪਸ਼ਟ ਕਮੇਟੀ ਕੰਮ ਲਈ ਬਣਾਇਆ ਗਿਆ।',
    'landing.collections': 'ਇਕੱਠ',
    'landing.expenses': 'ਖਰਚੇ',
    'landing.members': 'ਮੈਂਬਰ',
    'landing.surplus': 'ਬਚਤ',
    'landing.footer': '© 2026 SamitiBook. ਪਾਰਦਰਸ਼ੀ ਤਿਉਹਾਰ ਪ੍ਰਬੰਧਨ.',
  },
  as: {
    'app.tagline': 'স্বচ্ছ উৎসৱ পৰিচালনা',
    'landing.adminAccess': 'এডমিন পৰ্টেল প্ৰৱেশ',
    'landing.heroCopy': 'উৎসৱ সমিতিৰ বাবে সদস্য, সংগ্ৰহ, দান, খৰচ, ইনভেণ্টৰি আৰু যোগাযোগ স্পষ্টভাৱে পৰিচালনা কৰা সহজ আধুনিক ব্যৱস্থা।',
    'landing.liveOverview': 'লাইভ সাৰাংশ',
    'landing.capabilities': 'সুবিধাসমূহ',
    'landing.builtFor': 'স্পষ্ট সমিতি কামৰ বাবে নিৰ্মিত।',
    'landing.collections': 'সংগ্ৰহ',
    'landing.expenses': 'খৰচ',
    'landing.members': 'সদস্য',
    'landing.surplus': 'অধিক্য',
    'landing.footer': '© 2026 SamitiBook. স্বচ্ছ উৎসৱ পৰিচালনা.',
  },
  ur: {
    'app.tagline': 'شفاف تہوار انتظام',
    'landing.adminAccess': 'ایڈمن پورٹل رسائی',
    'landing.heroCopy': 'تہوار کمیٹیوں کے لیے اراکین، وصولی، عطیات، اخراجات، انوینٹری اور رابطے کو واضح انداز میں سنبھالنے والا سادہ جدید نظام۔',
    'landing.liveOverview': 'براہ راست خلاصہ',
    'landing.capabilities': 'صلاحیتیں',
    'landing.builtFor': 'واضح کمیٹی کام کے لیے بنایا گیا۔',
    'landing.collections': 'وصولیاں',
    'landing.expenses': 'اخراجات',
    'landing.members': 'اراکین',
    'landing.surplus': 'اضافی رقم',
    'landing.footer': '© 2026 SamitiBook. شفاف تہوار انتظام۔',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

function isLanguageCode(value: string | null): value is LanguageCode {
  return LANGUAGES.some(language => language.code === value);
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem(STORAGE_KEY);
    return isLanguageCode(saved) ? saved : 'en';
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ur' ? 'rtl' : 'ltr';
  }, [language]);

  const value = useMemo<LanguageContextType>(() => ({
    language,
    setLanguage,
    t: (key, params) => {
      let translation = landingText[language]?.[key] || translations[language]?.[key] || en[key as keyof typeof en] || key;
      if (params) {
        for (const [param, paramValue] of Object.entries(params)) {
          translation = translation.replace(`{{${param}}}`, String(paramValue));
        }
      }
      return translation;
    },
  }), [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
